<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Erich Gruhn" />


<title>Practical Machine Learning Project</title>

<script src="Practical_Machine_Learning_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="Practical_Machine_Learning_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="Practical_Machine_Learning_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="Practical_Machine_Learning_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="Practical_Machine_Learning_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="Practical_Machine_Learning_files/navigation-1.1/tabsets.js"></script>
<link href="Practical_Machine_Learning_files/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="Practical_Machine_Learning_files/highlightjs-1.1/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Practical Machine Learning Project</h1>
<h4 class="author"><em>Erich Gruhn</em></h4>
<h4 class="date"><em>4/13/2018</em></h4>

</div>


<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it.</p>
<p>In this project, we will use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants to predict the manner in which they did the exercise.</p>
</div>
<div id="data-preprocessing" class="section level2">
<h2>Data Preprocessing</h2>
<pre class="r"><code>library(caret)
library(rpart)
library(rpart.plot)
library(randomForest)
library(corrplot)
library(RGtk2)
library(cairoDevice)
library(rattle)</code></pre>
<div id="download-the-data" class="section level3">
<h3>Download the Data</h3>
<pre class="r"><code>trainUrl &lt;-&quot;https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv&quot;
testUrl &lt;- &quot;https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv&quot;
trainFile &lt;- &quot;./data/pml-training.csv&quot;
testFile  &lt;- &quot;./data/pml-testing.csv&quot;
if (!file.exists(&quot;./data&quot;)) {
  dir.create(&quot;./data&quot;)
}
if (!file.exists(trainFile)) {
  download.file(trainUrl, destfile=trainFile, method=&quot;curl&quot;)
}
if (!file.exists(testFile)) {
  download.file(testUrl, destfile=testFile, method=&quot;curl&quot;)
}</code></pre>
</div>
<div id="read-the-data" class="section level3">
<h3>Read the Data</h3>
<p>After downloading the data from the data source, we can read the two csv files into two data frames.</p>
<pre class="r"><code>trainRaw &lt;- read.csv(&quot;./data/pml-training.csv&quot;)
testRaw &lt;- read.csv(&quot;./data/pml-testing.csv&quot;)
dim(trainRaw)</code></pre>
<pre><code>## [1] 19622   160</code></pre>
<pre class="r"><code>dim(testRaw)</code></pre>
<pre><code>## [1]  20 160</code></pre>
<p>The training data set contains 19622 observations and 160 variables, while the testing data set contains 20 observations and 160 variables. The “classe” variable in the training set is the outcome to predict.</p>
</div>
<div id="clean-the-data" class="section level3">
<h3>Clean the data</h3>
<p>In this step, we will clean the data and get rid of observations with missing values as well as some meaningless variables.</p>
<pre class="r"><code>sum(complete.cases(trainRaw))</code></pre>
<pre><code>## [1] 406</code></pre>
<p>First, we remove columns that contain NA missing values.</p>
<pre class="r"><code>trainRaw &lt;- trainRaw[, colSums(is.na(trainRaw)) == 0] 
testRaw &lt;- testRaw[, colSums(is.na(testRaw)) == 0] </code></pre>
<p>Next, we get rid of some columns that do not contribute much to the accelerometer measurements.</p>
<pre class="r"><code>classe &lt;- trainRaw$classe
trainRemove &lt;- grepl(&quot;^X|timestamp|window&quot;, names(trainRaw))
trainRaw &lt;- trainRaw[, !trainRemove]
trainCleaned &lt;- trainRaw[, sapply(trainRaw, is.numeric)]
trainCleaned$classe &lt;- classe
testRemove &lt;- grepl(&quot;^X|timestamp|window&quot;, names(testRaw))
testRaw &lt;- testRaw[, !testRemove]
testCleaned &lt;- testRaw[, sapply(testRaw, is.numeric)]</code></pre>
<p>Now, the cleaned training data set contains 19622 observations and 53 variables, while the testing data set contains 20 observations and 53 variables. The “classe” variable is still in the cleaned training set.</p>
</div>
<div id="slice-the-data" class="section level3">
<h3>Slice the data</h3>
<p>Then, we can split the cleaned training set into a pure training data set (70%) and a validation data set (30%). We will use the validation data set to conduct cross validation in future steps.</p>
<pre class="r"><code>set.seed(22519) # For reproducibile purpose
inTrain &lt;- createDataPartition(trainCleaned$classe, p=0.70, list=F)
trainData &lt;- trainCleaned[inTrain, ]
testData &lt;- trainCleaned[-inTrain, ]</code></pre>
</div>
</div>
<div id="data-modeling" class="section level2">
<h2>Data Modeling</h2>
<p>We fit a predictive model for activity recognition using <strong>Random Forest</strong> algorithm because it automatically selects important variables and is robust to correlated covariates &amp; outliers in general. We will use <strong>5-fold cross validation</strong> when applying the algorithm.</p>
<pre class="r"><code>controlRf &lt;- trainControl(method=&quot;cv&quot;, 5)
modelRf &lt;- train(classe ~ ., data=trainData, method=&quot;rf&quot;, trControl=controlRf, ntree=250)
modelRf</code></pre>
<pre><code>## Random Forest 
## 
## 13737 samples
##    52 predictor
##     5 classes: &#39;A&#39;, &#39;B&#39;, &#39;C&#39;, &#39;D&#39;, &#39;E&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (5 fold) 
## Summary of sample sizes: 10989, 10991, 10988, 10989, 10991 
## Resampling results across tuning parameters:
## 
##   mtry  Accuracy   Kappa    
##    2    0.9909729  0.9885802
##   27    0.9914091  0.9891325
##   52    0.9849311  0.9809363
## 
## Accuracy was used to select the optimal model using the largest value.
## The final value used for the model was mtry = 27.</code></pre>
<p>Then, we estimate the performance of the model on the validation data set.</p>
<pre class="r"><code>predictRf &lt;- predict(modelRf, testData)
confusionMatrix(testData$classe, predictRf)</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 1673    0    0    0    1
##          B    6 1129    4    0    0
##          C    0    0 1021    5    0
##          D    0    0   15  948    1
##          E    0    0    0    6 1076
## 
## Overall Statistics
##                                           
##                Accuracy : 0.9935          
##                  95% CI : (0.9911, 0.9954)
##     No Information Rate : 0.2853          
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
##                                           
##                   Kappa : 0.9918          
##  Mcnemar&#39;s Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.9964   1.0000   0.9817   0.9885   0.9981
## Specificity            0.9998   0.9979   0.9990   0.9968   0.9988
## Pos Pred Value         0.9994   0.9912   0.9951   0.9834   0.9945
## Neg Pred Value         0.9986   1.0000   0.9961   0.9978   0.9996
## Prevalence             0.2853   0.1918   0.1767   0.1630   0.1832
## Detection Rate         0.2843   0.1918   0.1735   0.1611   0.1828
## Detection Prevalence   0.2845   0.1935   0.1743   0.1638   0.1839
## Balanced Accuracy      0.9981   0.9989   0.9903   0.9926   0.9984</code></pre>
<pre class="r"><code>accuracy &lt;- postResample(predictRf, testData$classe)
accuracy</code></pre>
<pre><code>##  Accuracy     Kappa 
## 0.9935429 0.9918320</code></pre>
<pre class="r"><code>oose &lt;- 1 - as.numeric(confusionMatrix(testData$classe, predictRf)$overall[1])
oose</code></pre>
<pre><code>## [1] 0.006457094</code></pre>
<p>So, the estimated accuracy of the model is 99.42% and the estimated out-of-sample error is 0.58%.</p>
</div>
<div id="predicting-for-test-data-set" class="section level2">
<h2>Predicting for Test Data Set</h2>
<p>Now, we apply the model to the original testing data set downloaded from the data source. We remove the <code>problem_id</code> column first.</p>
<pre class="r"><code>result &lt;- predict(modelRf, testCleaned[, -length(names(testCleaned))])
result</code></pre>
<pre><code>##  [1] B A B A A E D B A A B C B A E E A B B B
## Levels: A B C D E</code></pre>
</div>
<div id="appendix-figures" class="section level2">
<h2>Appendix: Figures</h2>
<ol style="list-style-type: decimal">
<li>Correlation Matrix Visualization</li>
</ol>
<pre class="r"><code>corrPlot &lt;- cor(trainData[, -length(names(trainData))])
corrplot(corrPlot, method=&quot;color&quot;)</code></pre>
<p><img src="Practical_Machine_Learning_files/figure-html/unnamed-chunk-12-1.png" width="1152" /> 2. Decision Tree Visualization</p>
<p>Included are both the “Fancy Tree Plot” - a little hard to read based on the number of leaves, and the “Fast Tree Plot” - somewhat easier to read.</p>
<pre class="r"><code>treeModel &lt;- rpart(classe ~ ., data=trainData, method=&quot;class&quot;)

fancyRpartPlot(treeModel, tweak = 1)</code></pre>
<p><img src="Practical_Machine_Learning_files/figure-html/unnamed-chunk-13-1.png" width="1152" /></p>
<pre class="r"><code>prp(treeModel) # fast plot</code></pre>
<p><img src="Practical_Machine_Learning_files/figure-html/unnamed-chunk-13-2.png" width="1152" /></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
